# Generated by Django 6.0.5 on 2026-05-28 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_planservicio_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Factura')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('OVERDUE', 'Vencida')], default='PENDING', max_length=20, verbose_name='Estado de Pago')),
                ('periodo_facturacion', models.CharField(max_length=50, verbose_name='Periodo de Facturación')),
                ('sat_uuid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='UUID de Facturación SAT')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Transacción Stripe')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='clients.clientprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('dia_cobro', models.IntegerField(default=1, verbose_name='Día de Cobro Mensual')),
                ('activa', models.BooleanField(default=True, verbose_name='Suscripción Activa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='clients.clientprofile', verbose_name='Cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='clients.planservicio', verbose_name='Plan Contratado')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
