"""
Django settings for fintech_core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    DEBUG=(bool, True)
)

# Read .env file if it exists
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-h-^(bi44y8!x#!itbc17w+ufq+)ssqbom^7dle=9_n19y4%0w$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'core',
    'accounting',
    'billing',
    'clients',
    'portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fintech_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fintech_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL setting with SQLite fallback
db_host = env('DB_HOST', default='')
db_name = env('DB_NAME', default='')

import sys
is_testing = 'test' in sys.argv

if not is_testing and db_host and db_name and db_host != 'db.tu-proyecto-supabase.supabase.co' and not db_host.startswith('tu_'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': env('DB_USER', default=''),
            'PASSWORD': env('DB_PASSWORD', default=''),
            'HOST': db_host,
            'PORT': env('DB_PORT', default='5432'),
            'OPTIONS': {
                'sslmode': 'require',
            }
        }
    }
    # Print database status on server startup
    if 'runserver' in sys.argv:
        print("Database: Connected to PostgreSQL (Supabase)")
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    if 'runserver' in sys.argv:
        print("Database: Using local SQLite database (Placeholder Supabase credentials detected)")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'core.User'
LOGIN_URL = 'portal:index'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'portal:index'


# -----------------------------------------------------------------------------
# SEGURIDAD TLS/HTTPS (solo en producción)
# Estas configuraciones fuerzan HTTPS y protegen cookies de sesión y CSRF.
# Se activan automáticamente cuando DEBUG=False (entorno de producción).
# -----------------------------------------------------------------------------
if not DEBUG:
    # Redirige todo el tráfico HTTP → HTTPS (TLS obligatorio)
    SECURE_SSL_REDIRECT = True

    # Las cookies de sesión (login) solo se envían por HTTPS
    SESSION_COOKIE_SECURE = True

    # La cookie CSRF solo se envía por HTTPS (protege formularios de pago)
    CSRF_COOKIE_SECURE = True

    # HSTS: le indica al navegador que SOLO acepte HTTPS por 1 año
    SECURE_HSTS_SECONDS = 31536000  # 1 año en segundos

    # Aplica HSTS también a todos los subdominios
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    # Permite registrar el dominio en la lista pública de HSTS de los navegadores
    SECURE_HSTS_PRELOAD = True

