# Generated by Django 6.0.5 on 2026-05-28 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('velocidad_mbps', models.IntegerField(verbose_name='Velocidad (Mbps)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Plan de Servicio',
                'verbose_name_plural': 'Planes de Servicio',
            },
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Perfil de Cliente', 'verbose_name_plural': 'Perfiles de Clientes'},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='codigo_referencia',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de Referencia SPEI'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='estado',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=20, verbose_name='Estado de Servicio'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='monto_saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Pendiente'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='correo_facturacion',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de Facturación'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='razon_social',
            field=models.CharField(max_length=255, verbose_name='Razón Social / Nombre'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='rfc',
            field=models.CharField(max_length=20, unique=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='clients.planservicio', verbose_name='Plan Contratado'),
        ),
    ]
