# Generated by Django 6.0.5 on 2026-05-28 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Transacción')),
                ('concepto', models.TextField(verbose_name='Concepto de Transferencia / SPEI')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso (Depósito / Abono)'), ('EGRESO', 'Egreso (Retiro / Cargo)')], default='INGRESO', max_length=20, verbose_name='Tipo de Operación')),
                ('estado', models.CharField(choices=[('PENDING', 'Pendiente de Conciliar'), ('CONCILIATED', 'Conciliado')], default='PENDING', max_length=20, verbose_name='Estado de Conciliación')),
                ('codigo_transaccion', models.CharField(max_length=100, unique=True, verbose_name='Código de Transacción Bancaria')),
                ('factura_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_banco', to='billing.factura', verbose_name='Factura Conciliada')),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
